//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mini_E_commerce_Aldakkaneh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public int order_item_id { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual IOrder IOrder { get; set; }
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
