//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mini_E_commerce_Aldakkaneh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Item = new HashSet<Order_Item>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int product_id { get; set; }
        public string SKU { get; set; }
        public string description { get; set; }
        public string imgprodect { get; set; }
        public decimal price { get; set; }
        public int stock { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
    public class ProductDetailsViewModel
    {
        public Product Product { get; set; }
        public List<Product> OtherProducts { get; set; }
    }

}
